---
output:
  html_document: default
  pdf_document: default
---

``` {r Load}
library(wesanderson)
library(ggplot2)
library(tidyverse)
library(fredr)
library(purrr)
library(lubridate)

#Package Manual
#  https://cran.r-project.org/web/packages/fredr/fredr.pdf

#color chart
# https://www.nceas.ucsb.edu/~frazier/RSpatialGuides/colorPaletteCheatsheet.pdf
```

``` {r key}
fredr_set_key("5e546bf9dc0d38cf6e2db34bb0e9dcef")
```
# R -----------------------------------------------------------------------

```{r REAL-GDP}
fredr_request(
  endpoint = "series/observations",
  series_id = "A191RL1Q225SBEA",
  observation_start = "2009-10-22",
  observation_end = "9999-01-01",
  frequency = "q",
  filter_variable = "seasonal_adjustment",
  units = "lin") %>%
  mutate(value = as.numeric(value))%>%
  mutate(date = ymd(date))%>%
 ggplot(mapping = aes( x = date, y = value)) + 
  geom_line( color = "black", size = 1.5)  +
  labs(title = "Real GDP", subtitle = "From October 2009 to Present", caption = "Source: Federal Reserve Bank of St. Louis", vjust = 1000)  +
  labs(x= "Date", y = "Percent Change" size = 10) +
  geom_hline(yintercept = 0, size = .75, color = "red", alpha = .5) +
  theme_test(base_size = 25) 
```


```{r Durables}
#Durables
fredr_request(
  endpoint = "series/observations",
  series_id = "PCDGCC96",
  observation_start = "2009-10-22",
  observation_end = "9999-01-01",
  frequency = "q",
  filter_variable = "seasonal_adjustment",
  units = "pch") %>%
  mutate(value = as.numeric(value))%>%
  mutate(date = ymd(date))%>%
 ggplot(mapping = aes( x = date, y = value)) + 
  geom_line( color = "black", size = 1.5)  +
  labs(title = "Durables", subtitle = "From October 2009 to Present", caption = "Source: Federal Reserve Bank of St. Louis", vjust = 1000)  +
  labs(x= "Date", y = "Percent Change", size = 10) +
  geom_hline(yintercept = 0, size = .75, color = "red", alpha = .5) +
  theme_test(base_size = 25) 
```

```{r non-Durables}
#Non-Durables
fredr_request(
  endpoint = "series/observations",
  series_id = "PCNDGC96",
  observation_start = "2009-10-22",
  observation_end = "9999-01-01",
  frequency = "q",
  filter_variable = "seasonal_adjustment",
  units = "pch") %>%
  mutate(value = as.numeric(value))%>%
  mutate(date = ymd(date))%>%
 ggplot(mapping = aes( x = date, y = value)) + 
  geom_line( color = "black", size = 1.5)  +
  labs(title = "Non-Durables", subtitle = "From October 2009 to Present", caption = "Source: Federal Reserve Bank of St. Louis", vjust = 1000)  +
  labs(x= "Date", y = "Percent Change", size = 10) +
  geom_hline(yintercept = 0, size = .75, color = "red", alpha = .5) +
  theme_test(base_size = 25) 
```

```{r Household_Consumption}
#Household Consumption
fredr_request(
  endpoint = "series/observations",
  series_id = "DPCERL1Q225SBEA",
  observation_start = "2009-10-22",
  observation_end = "9999-01-01",
filter_variable = "seasonal_adjustment",
  frequency = "q",
  units = "lin") %>%
  mutate(value = as.numeric(value))%>%
  mutate(date = ymd(date))%>%
 ggplot(mapping = aes( x = date, y = value)) + 
  geom_line( color = "black", size = 1.5)  +
  labs(title = "Household Consumption", subtitle = "From October 2009 to Present", caption = "Source: Federal Reserve Bank of St. Louis", vjust = 1000)  +
  labs(x= "Date", y = "Percent Change", size = 10) +
  geom_hline(yintercept = 0, size = .75, color = "red", alpha = .5) +
  theme_test(base_size = 25) 
```

```{r Investment}
#Investment
fredr_request(
  endpoint = "series/observations",
  series_id = "A006RL1Q225SBEA",
  observation_start = "2009-10-22",
  observation_end = "9999-01-01",
  frequency = "q",
  filter_variable = "seasonal_adjustment",
  units = "lin") %>%
  mutate(value = as.numeric(value))%>%
  mutate(date = ymd(date))%>%
 ggplot(mapping = aes( x = date, y = value)) + 
  geom_line( color = "black", size = 1.5)  +
  labs(title = "Investment", subtitle = "From October 2009 to Present",caption = "Source: Federal Reserve Bank of St. Louis", vjust = 1000)  +
  labs(x= "Date", y = "Percent Change") +
  geom_hline(yintercept = 0, size = .75, color = "red", alpha = .5) +
  theme_test(base_size = 25) 
```

```{r non-res-fixed}
#Real Private Nonresidential Fixed Investment
fredr_request(
  endpoint = "series/observations",
  series_id = "PNFIC1",
  observation_start = "2009-10-22",
  observation_end = "9999-01-01",
  frequency = "q",
  filter_variable = "seasonal_adjustment",
  units = "pch") %>%
  mutate(value = as.numeric(value))%>%
  mutate(date = ymd(date))%>%
 ggplot(mapping = aes( x = date, y = value)) + 
  geom_line( color = "black", size = 1.5)  +
  labs(title = "Non-Residential Fixed", subtitle = "From October 2009 to Present", caption = "Source: Federal Reserve Bank of St. Louis", vjust = 1000)  +
  labs(x= "Date", y = "Percent Change", size = 10) +
  geom_hline(yintercept = 0, size = .75, color = "red", alpha = .5) +
  theme_test(base_size = 25) 
```

```{r}
#Real Government Consumption Expenditures and Gross Investment
fredr_request(
  endpoint = "series/observations",
  series_id = "GCEC1",
  observation_start = "2009-10-22",
  observation_end = "9999-01-01",
  frequency = "q",
  filter_variable = "seasonal_adjustment",
  units = "pch") %>%
  mutate(value = as.numeric(value))%>%
  mutate(date = ymd(date))%>%
 ggplot(mapping = aes( x = date, y = value)) + 
  geom_line( color = "black", size = 1.5)  +
  labs(title = "Government Consumption", subtitle = "From October 2009 to Present", caption = "Source: Federal Reserve Bank of St. Louis", vjust = 1000)  +
  labs(x= "Date", y = "Percent Change", size = 10) +
  geom_hline(yintercept = 0, size = .75, color = "red", alpha = .5) +
  theme_test(base_size = 25) 
```

```{r net-export}
#Real Net Exports of Goods and Services
fredr_request(
  endpoint = "series/observations",
  series_id = "NETEXC",
  observation_start = "2009-10-22",
  observation_end = "9999-01-01",
  frequency = "q",
  filter_variable = "seasonal_adjustment",
  units = "pch") %>%
  mutate(value = as.numeric(value))%>%
  mutate(date = ymd(date))%>%
 ggplot(mapping = aes( x = date, y = value)) + 
  geom_line( color = "black", size = 1.5)  +
  labs(title = "Net Exports", subtitle = "From October 2009 to Present", caption = "Source: Federal Reserve Bank of St. Louis")  +
  labs(x= "Date", y = "Percent Change", size = 10) +
  geom_hline(yintercept = 0, size = .75, color = "red", alpha = .5) +
  theme_test(base_size = 25) 
```

```{r unemp}
#Unemployment rate
unemp <-fredr_request(
  endpoint = "series/observations",
  series_id = "UNRATE",
  observation_start = "2009-10-22",
  observation_end = "9999-01-01",
  frequency = "m",
  filter_variable = "seasonal_adjustment",
  units = "lin") %>%
  mutate(value = as.numeric(value))%>%
  mutate(date = ymd(date))
```

```{r u6}
#Total Unemployed, Plus All Marginally Attached Workers Plus Total Employed Part Time for Economic Reasons, as a Percent of All Civilian Labor Force Plus All Marginally Attached Workers 
u6 <-fredr_request(
  endpoint = "series/observations",
  series_id = "U6RATE",
  observation_start = "2009-10-22",
  observation_end = "9999-01-01",
  frequency = "m",
  filter_variable = "seasonal_adjustment",
  units = "lin") %>%
  mutate(value = as.numeric(value))%>%
  mutate(date = ymd(date))
```

```{r unemp-u6}
ggplot() + 
  geom_line( data = unemp, mapping = aes(x = date, y = value), color = "blue", size = 1.5)  +
  geom_line( data = u6, mapping = aes(x = date, y = value), color = "red", size = 1.5)  +
  labs(title = "Unemployment", subtitle = "From October 2009 to Present", caption = "Source: Federal Reserve Bank of St. Louis")+
  labs(x= "Date", y = "Rate", size = 10) +
  geom_hline(yintercept = 4.2, size = .75, color = "red", alpha = .5) +
  theme_test(base_size = 25) 
```



```{r LFP-rate}
#Civilian Labor Force Participation Rate: 25 to 54 years
fredr_request(
  endpoint = "series/observations",
  series_id = "LNS11300060",
  observation_start = "2009-10-22",
  observation_end = "9999-01-01",
  frequency = "m",
  filter_variable = "seasonal_adjustment",
  units = "pch") %>%
  mutate(value = as.numeric(value))%>%
  mutate(date = ymd(date))%>%
 ggplot(mapping = aes( x = date, y = value)) + 
  geom_line( color = "black", size = 1.5)  +
  labs(title = "Civilian Labor Force Participation", subtitle = "From October 2009 to Present", caption = "Source: Federal Reserve Bank of St. Louis", vjust = 1000)  +
  labs(x= "Date", y = "Percent Change", size = 10) +
  geom_hline(yintercept = 0, size = .75, color = "red", alpha = .5) +
  theme_test(base_size = 25) 
```

```{r unemployment-insurance}
#Unemployment insurance claims
fredr_request(
  endpoint = "series/observations",
  series_id = "ICSA",
  observation_start = "2009-10-22",
  observation_end = "9999-01-01",
  frequency = "m",
  filter_variable = "seasonal_adjustment",
  units = "pch") %>%
  mutate(value = as.numeric(value))%>%
  mutate(date = ymd(date))%>%
 ggplot(mapping = aes( x = date, y = value)) + 
  geom_line( color = "black", size = 1.5)  +
  labs(title = "Unemployment Insurance Claims", subtitle = "From October 2009 to Present", caption = "Source: Federal Reserve Bank of St. Louis", vjust = 1000)  +
  labs(x= "Date", y = "Percent Change", size = 10) +
  geom_hline(yintercept = 0, size = .75, color = "red", alpha = .5) +
  theme_test(base_size = 25) 
```

```{r payroll}
#All Employees, Total Non-farm payroll
fredr_request(
  endpoint = "series/observations",
  series_id = "PAYEMS",
  observation_start = "2009-10-22",
  observation_end = "9999-01-01",
  frequency = "m",
  filter_variable = "seasonal_adjustment",
  units = "pch") %>%
  mutate(value = as.numeric(value))%>%
  mutate(date = ymd(date))%>%
 ggplot(mapping = aes( x = date, y = value)) + 
  geom_line( color = "black", size = 1.5)  +
  labs(title = "Total Non-farm Payroll", subtitle = "From October 2009 to Present", caption = "Source: Federal Reserve Bank of St. Louis", vjust = 1000)  +
  labs(x= "Date", y = "Percent Change", size = 10) +
  geom_hline(yintercept = 0, size = .75, color = "red", alpha = .5) +
  theme_test(base_size = 25) 
```

```{r hourly-earnings}
#Average Hourly Earnings of All Employees
fredr_request(
  endpoint = "series/observations",
  series_id = "CES0500000003",
  observation_start = "2009-10-22",
  observation_end = "9999-01-01",
  frequency = "m",
  filter_variable = "seasonal_adjustment",
  units = "pch") %>%
  mutate(value = as.numeric(value))%>%
  mutate(date = ymd(date))%>%
 ggplot(mapping = aes( x = date, y = value)) + 
  geom_line( color = "black", size = 1.5)  +
  labs(title = "Average Hourly Earnings", subtitle = "From October 2009 to Present", caption = "Source: Federal Reserve Bank of St. Louis", vjust = 1000)  +
  labs(x= "Date", y = "Percent Change", size = 10) +
  geom_hline(yintercept = 0, size = .75, color = "red", alpha = .5) +
  theme_test(base_size = 25) 
```

```{r new-housing-permits}
#New private housing units authorized
fredr_request(
  endpoint = "series/observations",
  series_id = "PERMIT",
  observation_start = "2009-10-22",
  observation_end = "9999-01-01",
  frequency = "m",
  filter_variable = "seasonal_adjustment",
  units = "pch") %>%
  mutate(value = as.numeric(value))%>%
  mutate(date = ymd(date))%>%
 ggplot(mapping = aes( x = date, y = value)) + 
  geom_line( color = "black", size = 1.5)  +
  labs(title = "New Private Housing Permits", subtitle = "From October 2009 to Present", caption = "Source: Federal Reserve Bank of St. Louis", vjust = 1000)  +
  labs(x= "Date", y = "Percent Change", size = 10) +
  geom_hline(yintercept = 0, size = .75, color = "red", alpha = .5) +
  theme_test(base_size = 25) 
```

```{r g}
#Real Government Consumption Expenditures and Gross Investment
fredr_request(
  endpoint = "series/observations",
  series_id = "GCEC1",
  observation_start = "2009-10-22",
  observation_end = "9999-01-01",
  frequency = "q",
  filter_variable = "seasonal_adjustment",
  units = "pch") %>%
  mutate(value = as.numeric(value))%>%
  mutate(date = ymd(date))%>%
 ggplot(mapping = aes( x = date, y = value)) + 
  geom_line( color = "black", size = 1.5)  +
  labs(title = "  ", subtitle = "From October 2009 to Present", caption = "Source: Federal Reserve Bank of St. Louis", vjust = 1000)  +
  labs(x= "Date", y = "Percent Change", size = 10) +
  geom_hline(yintercept = 0, size = .75, color = "red", alpha = .5) +
  theme_test(base_size = 25) 
```

```{r PCE-core}
#PCE core
pcecore<-fredr_request(
  endpoint = "series/observations",
  series_id = "PCEPI",
  observation_start = "2009-10-22",
  observation_end = "9999-01-01",
  frequency = "m",
  filter_variable = "seasonal_adjustment",
  units = "pch") %>%
  mutate(value = as.numeric(value))%>%
  mutate(date = ymd(date))
```

```{r PCE-headline}
#PCE headline
pcehead <- fredr_request(
  endpoint = "series/observations",
  series_id = "PCEPILFE",
  observation_start = "2009-10-22",
  observation_end = "9999-01-01",
  frequency = "m",
  filter_variable = "seasonal_adjustment",
  units = "pch") %>%
  mutate(value = as.numeric(value))%>%
  mutate(date = ymd(date))
```

```{r both}
ggplot() + 
  geom_line(data = pcecore, mapping = aes( x = date, y = value), color = "blue", size = 1.5)  +
  geom_line(data = pcehead, mapping = aes( x = date, y = value), color = "red", size = 1.5)  +
  labs(title = "  ", subtitle = "From October 2009 to Present", caption = "Source: Federal Reserve Bank of St. Louis", vjust = 1000)  +
  labs(x= "Date", y = "Percent Change", size = 10) +
  geom_hline(yintercept = 0, size = .75, color = "red", alpha = .5) +
  theme_test(base_size = 25) 
```
#in my oppinion that is a MESS! lets just use the headline beause there is not that much of a difference in the past 4 years I am leaving it for now incase there is substancial disagreement
```{r pceheadline}
fredr_request(
  endpoint = "series/observations",
  series_id = "PCEPILFE",
  observation_start = "2009-10-22",
  observation_end = "9999-01-01",
  frequency = "m",
  filter_variable = "seasonal_adjustment",
  units = "pch") %>%
  mutate(value = as.numeric(value))%>%
  mutate(date = ymd(date))%>%
 ggplot(mapping = aes( x = date, y = value)) + 
  geom_line( color = "black", size = 1.5)  +
  labs(title = "Headline PCE", subtitle = "From October 2009 to Present", caption = "Source: Federal Reserve Bank of St. Louis", vjust = 1000)  +
  labs(x= "Date", y = "Percent Change", size = 10) +
  geom_hline(yintercept = 0, size = .75, color = "red", alpha = .5) +
  theme_test(base_size = 25) 
```

```{r Capacity-Utilization}
#Capacity Utilization 
fredr_request(
  endpoint = "series/observations",
  series_id = "TCU",
  observation_start = "2009-10-22",
  observation_end = "9999-01-01",
  frequency = "m",
  filter_variable = "seasonal_adjustment",
  units = "pch") %>%
  mutate(value = as.numeric(value))%>%
  mutate(date = ymd(date))%>%
 ggplot(mapping = aes( x = date, y = value)) + 
  geom_line( color = "black", size = 1.5)  +
  labs(title = "Capacity Utilization", subtitle = "From October 2009 to Present", caption = "Source: Federal Reserve Bank of St. Louis", vjust = 1000)  +
  labs(x= "Date", y = "Percent Change", size = 10) +
  geom_hline(yintercept = 0, size = .75, color = "red", alpha = .5) +
  theme_test(base_size = 25) 
```

#this is an idea on presenting repo rates, two graphs shows a very flat market spiking

```{r REPO-market-b4}
#repo
fredr_request(
  endpoint = "series/observations",
  series_id = "SOFR",
  observation_start = "2000-06-01",
  observation_end = "2019-09-15",
  frequency = "d",
  filter_variable = "seasonal_adjustment",
  units = "lin") %>%
  mutate(value = as.numeric(value))%>%
  mutate(date = ymd(date))%>%
 ggplot(mapping = aes( x = date, y = value)) + 
  geom_line( color = "black", size = .5) +
  geom_line( color = "deepskyblue", size = .2)  +
  geom_jitter( size = .1, color = "black", alpha = .1) +
  geom_smooth(size = .5)+
  labs(title = "Percent change", subtitle = "From October 2009 to Present", caption = "Source: Federal Reserve Bank of St. Louis", vjust = 1000)  +
  labs( x= "Date", y = "Percent Change") +
  geom_hline(yintercept = 0, size = .1, color = "black", alpha = 1)+
  theme_test(base_size = 25) 
```

```{r REPO-market}
#repo
fredr_request(
  endpoint = "series/observations",
  series_id = "SOFR",
  observation_start = "2000-06-01",
  observation_end = "9999-01-01",
  frequency = "d",
  filter_variable = "seasonal_adjustment",
  units = "lin") %>%
  mutate(value = as.numeric(value))%>%
  mutate(date = ymd(date))%>%
 ggplot(mapping = aes( x = date, y = value)) + 
  geom_line( color = "black", size = .5) +
  geom_line( color = "deepskyblue", size = .2)  +
  geom_jitter( size = .1, color = "black", alpha = .1) +
  geom_smooth(size = .5)+
  labs(title = "Percent change", subtitle = "From October 2009 to Present", caption = "Source: Federal Reserve Bank of St. Louis", vjust = 1000)  +
  labs( x= "Date", y = "Percent Change") +
  geom_hline(yintercept = 0, size = .1, color = "black", alpha = 1)+
  theme_test(base_size = 25) 
```


```{r Monetary-Base}
#Monetaty Base
fredr_request(
  endpoint = "series/observations",
  series_id = "BASE",
  observation_start = "2009-10-22",
  observation_end = "2020-09-15",
  frequency = "m",
  filter_variable = "seasonal_adjustment",
  units = "pch") %>%
  mutate(value = as.numeric(value))%>%
  mutate(date = ymd(date))%>%
  mutate(value = as.numeric(value))%>%
  mutate(date = ymd(date))%>%
 ggplot(mapping = aes( x = date, y = value)) + 
  geom_line( color = "black", size = 1.5)  +
  labs(title = "Monetaty Base", subtitle = "From October 2009 to Present", caption = "Source: Federal Reserve Bank of St. Louis", vjust = 1000)  +
  labs(x= "Date", y = "Percent Change", size = 10) +
  geom_hline(yintercept = 0, size = .75, color = "red", alpha = .5) +
  theme_test(base_size = 25) 
```
```{r }
#Federal Funds Rate
fredr_request(
  endpoint = "series/observations",
  series_id = "FEDFUNDS",
  observation_start = "2009-10-22",
  observation_end = "2020-09-15",
  frequency = "m",
  filter_variable = "seasonal_adjustment",
  units = "lin") %>%
  mutate(value = as.numeric(value))%>%
  mutate(date = ymd(date))%>%
  mutate(value = as.numeric(value))%>%
  mutate(date = ymd(date))%>%
 ggplot(mapping = aes( x = date, y = value)) + 
  geom_line( color = "black", size = 1.5)  +
  labs(title = "Federal Funds Rate", subtitle = "From October 2009 to Present", caption = "Source: Federal Reserve Bank of St. Louis", vjust = 1000)  +
  labs(x= "Date", y = "Rate", size = 10) +
  geom_hline(yintercept = 0, size = .75, color = "red", alpha = .5) +
  theme_test(base_size = 25) 
```

```{r Prime-Rate}
#Prime Lending Rate
fredr_request(
  endpoint = "series/observations",
  series_id = "DPRIME",
  observation_start = "2009-10-22",
  observation_end = "2020-09-15",
  frequency = "w",
  filter_variable = "seasonal_adjustment",
  units = "lin") %>%
  mutate(value = as.numeric(value))%>%
  mutate(date = ymd(date))%>%
  mutate(value = as.numeric(value))%>%
  mutate(date = ymd(date))%>%
 ggplot(mapping = aes( x = date, y = value)) + 
  geom_line( color = "black", size = 1.5)  +
  labs(title = "Prime Lending Rate", subtitle = "From October 2009 to Present", caption = "Source: Federal Reserve Bank of St. Louis", vjust = 1000)  +
  labs(x= "Date", y = "Percent Change", size = 10) +
  geom_hline(yintercept = 0, size = .75, color = "red", alpha = .5) +
  theme_test(base_size = 25) 
```


```{r Yield-Curve}
#Yield Curve 10-year/2-year
fredr_request(
  endpoint = "series/observations",
  series_id = "T10Y2Y",
  observation_start = "2009-10-22",
  observation_end = "2020-09-15",
  frequency = "m",
  filter_variable = "seasonal_adjustment",
  units = "lin") %>%
  mutate(value = as.numeric(value))%>%
  mutate(date = ymd(date))%>%
  mutate(value = as.numeric(value))%>%
  mutate(date = ymd(date))%>%
 ggplot(mapping = aes( x = date, y = value)) + 
  geom_line( color = "black", size = 1.5)  +
  labs(title = "Yield Curve", subtitle = "From October 2009 to Present", caption = "Source: Federal Reserve Bank of St. Louis", vjust = 1000)  +
  labs(x= "Date", y = "Percent Change", size = 10) +
  geom_hline(yintercept = 0, size = .75, color = "red", alpha = .5) +
  theme_test(base_size = 25) 
```

